// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjTcqHfAcJ119eCs2dJT4E2oz2ohDQFIA',
    appId: '1:949090336471:web:c197f127a921e668173a92',
    messagingSenderId: '949090336471',
    projectId: 'reddit-clone-c5b36',
    authDomain: 'reddit-clone-c5b36.firebaseapp.com',
    storageBucket: 'reddit-clone-c5b36.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnf6JeuA8aVdbXZokiLZeYjs7-qi1wnIY',
    appId: '1:949090336471:android:7e26ad955d418683173a92',
    messagingSenderId: '949090336471',
    projectId: 'reddit-clone-c5b36',
    storageBucket: 'reddit-clone-c5b36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwOqQxM8NXD2YEi29Z5bz__ymvKYadL2Q',
    appId: '1:949090336471:ios:1d96ad2053451754173a92',
    messagingSenderId: '949090336471',
    projectId: 'reddit-clone-c5b36',
    storageBucket: 'reddit-clone-c5b36.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwOqQxM8NXD2YEi29Z5bz__ymvKYadL2Q',
    appId: '1:949090336471:ios:1d96ad2053451754173a92',
    messagingSenderId: '949090336471',
    projectId: 'reddit-clone-c5b36',
    storageBucket: 'reddit-clone-c5b36.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjTcqHfAcJ119eCs2dJT4E2oz2ohDQFIA',
    appId: '1:949090336471:web:09fbfe67ab1e5c37173a92',
    messagingSenderId: '949090336471',
    projectId: 'reddit-clone-c5b36',
    authDomain: 'reddit-clone-c5b36.firebaseapp.com',
    storageBucket: 'reddit-clone-c5b36.appspot.com',
  );
}
